services:
  - type: web
    name: geomind-frontend

    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://SEU-BACKEND-ORIGIN/api/v1
      - key: VITE_BACKEND_URL
        value: https://SEU-BACKEND-ORIGIN